#pragma once
#include "standard_error_handling.h"

enum matrix_error {
	MATRICES_ARE_NOT_COMPATIBLE_FOR_ADDITION = 1,
	ELEMENT_SUBSCRIPT_IS_INVALID,
	ROW_SUBSCRIPT_IS_INVALID,
	COLUMN_SUBSCRIPT_IS_INVALID,
	ROW_WIDTH_IS_INVALID,
	COLUMN_HEIGHT_IS_INVALID,
	MATRIX_IS_NOT_SQUARE,
	MATRICES_ARE_NOT_COMPATIBLE_FOR_MULTIPLICATION,
	DIVISION_BY_ZERO,
	MATRICES_ARE_NOT_COMPATIBLE_FOR_HORIZONTAL_ATTACHMENT,
	MATRICES_ARE_NOT_COMPATIBLE_FOR_VERTICAL_ATTACHMENT,
	MATRIX_IS_SINGULAR,
	SUBMATRIX_CORNER_SUBSCRIPTS_ARE_INVALID,
	MATRIX_IS_VOID,
	THE_STRING_IS_NOT_A_VALID_SUBSCRIPT,
	MINOR_SHULD_BE_SQUARE,
	MINOR_IS_VOID,
	MINOR_ROW_SUBSCRIPT_IS_INVALID,
	MINOR_COLUMN_SUBSCRIPT_IS_INVALID,
	MINOR_PATTERN_IS_NOT_SUITABLE_FOR_THE_MATRIX
};

const char *matrix_err_list[];

void catch_matrix_exception(matrix_error err_num);